### ISSUE TITLE
Seperator vs Separator

### ISSUE THREAD

**Issue by icagstrout** [chrissrogers/grunt-wrap#18]
Your readme has "seperator" in the example (typo?) the task uses the correct spelling of "separator"

just FYI :)

**Comment by m-blattner** [comment]
I'm just a random dude having made the same spelling error and which has found this page to be a top result when searched for "seperator or separator".

just FYI :)

**Comment by DiamondCoder1000** [comment]
Nnbhgvmhvmjbmjh

**Comment by sussybakafromamogus** [comment]
amorgos
